### ISSUE TITLE
New operations needed!

### ISSUE THREAD

**Issue by FFjet** [ncu571633/midi_parser#2]
Can it delete events?
I'd appreciate it if the function is added to the MIDI Parser!:D

**Comment by ncu571633** [comment]
Currently the event is stored in a List/Vector. If you want to delete an event, you need to specify the index of this event, or you need to specify a key(say the pitch of this event). Which do you want, can you show an example?

**Comment by Leoleepz** [comment]
Well for example I want to delete superimposed midi notes. You may know **Black MIDIs**, some of which contains lots of lags and I want to clear the lags without destroying the midi arts

**Comment by ncu571633** [comment]
API used to delete event is added as below:
bool MidiFile::deleteTrackEvent(int trackNumber, EventType t, int v1, int v2, int v3=0, int v4=0, int v5=0);

**Comment by Leoleepz** [comment]
I see, thx
btw, is there any APIs to help create midi events?
I thought `setNoteOff` and `setNoteOn` may help modify them, but why `trackChunks` is private and I can't access these operations?

**Comment by ncu571633** [comment]
The idea is that it is hard to modify midi event manually. So you can define all midi events in a txt file, then they are imported into the internal data structure. In this way, the APIs used to modify midi is limited. 
However, these APIs could be added upon requests.

**Comment by Leoleepz** [comment]
Well, I thought I was able to look up all the tracks and events. As the events' information is stored in a vector, I can use `for` cycle to traverse these events in a track. Is it possible that when I specified a tracknumber and event number(its position in each `vector` struct), I can modify it through your APIs?

**Comment by ncu571633** [comment]
The following function is added to edit the edit:
bool MidiFile::editTrackEvent(size_t trackIndex, size_t eventIndex, EventType t, int v1, int v2, int v3=0, int v4=0, int v5=0);
